### ISSUE TITLE
About evaluation results

### ISSUE THREAD

**Issue by uyoung-jeong** [xy02-05/ScoreHypo#2]
Hello, your work is greatly impressive, and thank you for sharing the code.
I ran the evaluation code, but don't know how to interpret the evaluation results.

1. There are four different values for each metric. For example, your code shows mpjpe, mpjpe_select, and mpjpe_z0, and mpjpe_mean.
Can you explain that which metric was used to report the performance in the main paper?

2. Results of the main paper does not match with my evaluation results.
For example, I ran Scorenet evaluation on 3DPW with 10 hypotheses, and got the result like this:
```
3dpw: eval mpjpe:65.9mm,         mpjpe_select:72.7mm,  mpjpe_z0:73.3mm mpjpe_mean:73.5
3dpw: eval pa-mpjpe:39.5mm,      pa-mpjpe_select:44.2mm,  pa-mpjpe_z0:44.3mm pa-mpjpe_mean:44.5
3dpw: eval pve:76.2mm,   pve_select:84.4mm,  pve_z0:85.4mm pve_mean:85.3
```
However, the main paper reports 79.8mm MPVPE, 68.5 MPJPE, 41.0 PA-MPJPE.

I also provide h36m evaluation result with 10 hypotheses:
```
h36m: eval mpjpe:41.8mm,         mpjpe_select:46.6mm,  mpjpe_z0:47.5mm mpjpe_mean:47.4
h36m: eval pa-mpjpe:28.4mm,      pa-mpjpe_select:31.9mm,  pa-mpjpe_z0:32.5mm pa-mpjpe_mean:32.4
h36m: eval pve:52.1mm,   pve_select:57.9mm,  pve_z0:59.1mm pve_mean:59.2
```
The main paper reports 52.5 MPVPE, 42.4 MPJPE, 29.0 PA-MPJPE.

It seems that clarification is needed to correctly understand your great work.

**Comment by xy02-05** [comment]
Hi, thanks for your interest!
1. In the reported metrics, the first value (e.g., mpjpe) reports the min error of the M hypotheses, the second value (mpjpe_select) reports the error of the result selected by ScoreNet, the third value (mpjpe_z0) reports the error of the hypothesis generated by zero noise, and the fourth value (mpjpe_mean) reports the error of the mean of all hypotheses. Table 1 corresponds to the first metric (e.g., mpjpe), Table 2 corresponds to the third metric (e.g., mpjpe_z0), Table 3 reports all four metrics, and Table 4 corresponds to the second metric (e.g., mpjpe_select), as mentioned in the experiment section. 
2. The slight differences between your results and the paper may be due to differences in settings or randomness, and the discrepancies seem small, possibly even slightly better in some cases.

**Comment by uyoung-jeong** [comment]
Thank you for the detailed answer!
